version: '3.7'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3001:3000'
    networks:
      - service_net
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - db
    environment:
      NODE_ENV: development
      POSTGRES_PASSWORD: dummypass
      POSTRES_DB: dev-db
      POSTGRES_USER: jelkand
      POSTGRES_HOST: host.docker.internal

  ci:
    build:
      context: .
      dockerfile: Dockerfile
    image: ilm-post-service
    ports:
      - '3001:3000'
    networks:
      - service_net
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      NODE_ENV: production
      POSTGRES_PASSWORD: fnord
      POSTRES_DB: fnord
      POSTGRES_USER: fnord

  db:
    image: postgres:11.5-alpine
    networks:
      - service_net
    environment:
      POSTGRES_PASSWORD: dummypass
      POSTRES_DB: dev-db
      POSTGRES_USER: jelkand
    volumes:
      - /var/lib/postgresql/data

networks:
  service_net:
